
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Mar 14 00:09:43 GMT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHARLITERAL = 31;
  public static final int DIVIDE = 5;
  public static final int GTEQ = 15;
  public static final int LBRACKET = 25;
  public static final int POWER = 7;
  public static final int BOOLEANLITERAL = 32;
  public static final int CHAR = 37;
  public static final int LTEQ = 14;
  public static final int CONCAT = 3;
  public static final int INTEGER = 29;
  public static final int LPAREN = 20;
  public static final int SEMI = 18;
  public static final int INT = 34;
  public static final int MINUS = 4;
  public static final int FLOATLITERAL = 33;
  public static final int RPAREN = 21;
  public static final int AND = 17;
  public static final int LT = 12;
  public static final int TDEF = 54;
  public static final int IN = 8;
  public static final int BOOL = 38;
  public static final int COMMA = 19;
  public static final int PLUS = 2;
  public static final int IF = 45;
  public static final int MAIN = 42;
  public static final int ID = 44;
  public static final int DOT = 27;
  public static final int EOF = 0;
  public static final int RETURN = 49;
  public static final int RBRACKET = 26;
  public static final int error = 1;
  public static final int LINE = 28;
  public static final int VOID = 43;
  public static final int EQ = 9;
  public static final int TIMES = 6;
  public static final int FOREACH = 48;
  public static final int COLON = 24;
  public static final int ELSE = 46;
  public static final int DICT = 40;
  public static final int LBRACE = 22;
  public static final int EQQ = 10;
  public static final int READ = 51;
  public static final int WHILE = 47;
  public static final int LIST = 39;
  public static final int FLOAT = 36;
  public static final int RBRACE = 23;
  public static final int LEN = 41;
  public static final int STRING = 35;
  public static final int NEGATE = 16;
  public static final int DEF = 53;
  public static final int STRINGLITERAL = 30;
  public static final int GT = 13;
  public static final int PRINT = 52;
  public static final int DO = 50;
  public static final int NOTEQ = 11;
}

