
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Mar 10 19:54:41 GMT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHARLITERAL = 27;
  public static final int DIVIDE = 5;
  public static final int GTEQ = 15;
  public static final int POWER = 7;
  public static final int BOOLEANLITERAL = 28;
  public static final int CHAR = 33;
  public static final int LTEQ = 14;
  public static final int CONCAT = 3;
  public static final int INTEGER = 25;
  public static final int LPAREN = 20;
  public static final int SEMI = 18;
  public static final int INT = 30;
  public static final int MINUS = 4;
  public static final int FLOATLITERAL = 29;
  public static final int RPAREN = 21;
  public static final int AND = 17;
  public static final int LT = 12;
  public static final int TDEF = 50;
  public static final int IN = 8;
  public static final int BOOL = 34;
  public static final int COMMA = 19;
  public static final int PLUS = 2;
  public static final int IF = 41;
  public static final int MAIN = 38;
  public static final int ID = 40;
  public static final int EOF = 0;
  public static final int RETURN = 45;
  public static final int error = 1;
  public static final int VOID = 39;
  public static final int EQ = 9;
  public static final int TIMES = 6;
  public static final int FOREACH = 44;
  public static final int COLON = 24;
  public static final int ELSE = 42;
  public static final int DICT = 36;
  public static final int LBRACE = 22;
  public static final int EQQ = 10;
  public static final int READ = 47;
  public static final int WHILE = 43;
  public static final int LIST = 35;
  public static final int FLOAT = 32;
  public static final int RBRACE = 23;
  public static final int LEN = 37;
  public static final int NEGATE = 16;
  public static final int STRING = 31;
  public static final int DEF = 49;
  public static final int STRINGLITERAL = 26;
  public static final int GT = 13;
  public static final int PRINT = 48;
  public static final int DO = 46;
  public static final int NOTEQ = 11;
}

